@baseUrl = http://localhost/api

### 🔹 Create a new text
POST {{baseUrl}}/texts
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZ29vZ2xlSWQiOiIxMTI4ODg0OTYwMzU4MjMwMjk5MTciLCJlbWFpbCI6ImFua29uYmlzd2Fzc29wbmlsMTBAZ21haWwuY29tIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jS3hjdUtiMmZkTkh2YUVXdm5BeTBrcERONEQ1eTJma2hmc05oeFFlbGZuMExtRy1Ic1M9czk2LWMiLCJuYW1lIjoiQW5rb24gQmlzd2FzIiwiaWF0IjoxNzQ4ODYxNDgwLCJleHAiOjE3NDk0NjYyODB9.pshmST-wpC0FGjxwnk-mQfPGmFusriTWet8H8-0Fefw

{
  "content": "This is a valid content string with more than 10 characters."
}

### 🔹 Get a text by ID
GET {{baseUrl}}/texts/12
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZ29vZ2xlSWQiOiIxMTI4ODg0OTYwMzU4MjMwMjk5MTciLCJlbWFpbCI6ImFua29uYmlzd2Fzc29wbmlsMTBAZ21haWwuY29tIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jS3hjdUtiMmZkTkh2YUVXdm5BeTBrcERONEQ1eTJma2hmc05oeFFlbGZuMExtRy1Ic1M9czk2LWMiLCJuYW1lIjoiQW5rb24gQmlzd2FzIiwiaWF0IjoxNzQ4ODYxNDgwLCJleHAiOjE3NDk0NjYyODB9.pshmST-wpC0FGjxwnk-mQfPGmFusriTWet8H8-0Fefw

### 🔹 Update a text by ID
PUT {{baseUrl}}/texts/12
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZ29vZ2xlSWQiOiIxMTI4ODg0OTYwMzU4MjMwMjk5MTciLCJlbWFpbCI6ImFua29uYmlzd2Fzc29wbmlsMTBAZ21haWwuY29tIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jS3hjdUtiMmZkTkh2YUVXdm5BeTBrcERONEQ1eTJma2hmc05oeFFlbGZuMExtRy1Ic1M9czk2LWMiLCJuYW1lIjoiQW5rb24gQmlzd2FzIiwiaWF0IjoxNzQ4ODYxNDgwLCJleHAiOjE3NDk0NjYyODB9.pshmST-wpC0FGjxwnk-mQfPGmFusriTWet8H8-0Fefw

{
  "content": "This is the updated content for the text."
}

### 🔹 Delete a text by ID
DELETE {{baseUrl}}/texts/12
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZ29vZ2xlSWQiOiIxMTI4ODg0OTYwMzU4MjMwMjk5MTciLCJlbWFpbCI6ImFua29uYmlzd2Fzc29wbmlsMTBAZ21haWwuY29tIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jS3hjdUtiMmZkTkh2YUVXdm5BeTBrcERONEQ1eTJma2hmc05oeFFlbGZuMExtRy1Ic1M9czk2LWMiLCJuYW1lIjoiQW5rb24gQmlzd2FzIiwiaWF0IjoxNzQ4ODYxNDgwLCJleHAiOjE3NDk0NjYyODB9.pshmST-wpC0FGjxwnk-mQfPGmFusriTWet8H8-0Fefw

### 🔹 Get analysis for a text by ID
GET {{baseUrl}}/texts/9/analysis
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZ29vZ2xlSWQiOiIxMTI4ODg0OTYwMzU4MjMwMjk5MTciLCJlbWFpbCI6ImFua29uYmlzd2Fzc29wbmlsMTBAZ21haWwuY29tIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jS3hjdUtiMmZkTkh2YUVXdm5BeTBrcERONEQ1eTJma2hmc05oeFFlbGZuMExtRy1Ic1M9czk2LWMiLCJuYW1lIjoiQW5rb24gQmlzd2FzIiwiaWF0IjoxNzQ4ODYxNDgwLCJleHAiOjE3NDk0NjYyODB9.pshmST-wpC0FGjxwnk-mQfPGmFusriTWet8H8-0Fefw

